- .github/CODEOWNERS
- .github/pull_request_template.md
- README.md
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-1933)
Update the readme to remove skeleton specific comments
updated codeowners to our team
update the template to add in Jira URL and remove Trello reference
I have also set the teams with access to match those for CCQ, this includes LAA Admin and Security teams etc
these can be checked here:
https://github.com/ministryofjustice/laa-manage-your-civil-cases/settings/access
> EL-1933 update readme and codeowners

- deploy/laa-manage-your-civil-cases/values/production.yaml
- deploy/laa-manage-your-civil-cases/values/staging.yaml
- deploy/laa-manage-your-civil-cases/values/uat.yaml
main deploy is broken as I have not set the ingress and host
this PR adds values for the ingress and host for deployments to main UAT, STG and PROD deployments
> Bugfix: add ingress for main deployments

- deploy/laa-manage-your-civil-cases/values/production.yaml
- deploy/laa-manage-your-civil-cases/values/staging.yaml
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-XXXX)
added in a service name for stg and prod values file as deploy was failing because this was missing:
https://github.com/ministryofjustice/laa-manage-your-civil-cases/actions/runs/14612199105
> Bugfix: add service name to values for stg and prod deploys

- .github/workflows/deploy.yml
- deploy/laa-manage-your-civil-cases/values/production.yaml
- deploy/laa-manage-your-civil-cases/values/staging.yaml
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-XXXX)
make prod deploy dependent on successful staging deploy
fix indenting
May still be an issue with the ingress naming on deploy
> Bugfix: Tweak pipeline

- scripts/deploy.sh
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-XXXX)
deploy says the ingress name is wrong, but it matches the required format and UAT has deployed with the same format so I need to check we are in the correct namespace. I am also outputting the information required to do a manual deploy so I dont need to merge a PR every time i want to test staging
I have added/removed/altered:
-->
> debug staging deploy

- .github/workflows/deploy.yml
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-2243)
GA needs env specific secrets, this sets the env for each of the deploys
> Add envs to deployments

- .github/workflows/deploy.yml
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-2243)
This adds slack integration to the github action deployment pipeline
only adds notifications for STG and PROD as otherwise we would get a message for every commit pushed to github and the channel would become noisy. STG and PROD have fewer deploys so their alerts channels will be fine.
we only notify on failure.
> Add slack integration to github actions

- .husky/pre-commit
- README.md
- deploy/laa-manage-your-civil-cases/templates/deployment.yaml
- deploy/laa-manage-your-civil-cases/values/production.yaml
- deploy/laa-manage-your-civil-cases/values/staging.yaml
- deploy/laa-manage-your-civil-cases/values/uat.yaml
- index.js
- package-lock.json
- package.json
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-2245)
- I have added `husky` & `lint-staged` (which applies eslint to staged commits)
- As a bonus I have added in some missing `env` values from production
> EL-2245: Pre-commit hook with `husky` & `lint-staged`

- .github/workflows/publish-documentation.yml
- docs/README.md
- docs/config/tech-docs.yml
- docs/source/documentation/index.html.md.erb
- docs/source/index.html.md.erb
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-2276)
- If applied, this updates the settings for for using the `.github/workflows/publish-documentation.yml` workflow.
- n/a
> EL-2276: Finish off Github actions job for pushing tech docs

- .github/workflows/publish-documentation.yml
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-2276)
- If applied this excludes checking for an asset, which we do not use and no longer on `govuk-frontend`
- n/a
> EL-2276: Finish off Github actions job for pushing tech docs, Part 2

- .github/workflows/publish-documentation.yml
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-2276)
- If applied, this uses the same syntax as `laa-cvil-case-api`
- n/a
> BUG: EL-2276: Finish off Github actions job for pushing tech docs, Part 3

- .husky/pre-commit
- README.md
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-2245)
- I have removed the `.husky/pre-commit` file, as this is not needed. 
- When running `npx husky install` there is already a default version which we should be using. 
- this is a continuation of the EL-2245
> BUG: EL-2245: remove `.husky/pre-commit` file and go with version when initialised

- .github/workflows/deploy.yml
- scripts/deploy.sh
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-XXXX)
Removes a lot of the duplication in the github action, specifically:
creates a build-image job that is used by all three deployment jobs, previously we were building and pushing a new image for  each namespace, which does not help reproducibility. Now one image is built and pushed to the ECR and that image is used for all associated deploys. So for a UAT feature branch it will just be used once, but when that branch is merged to main, the image is used for UAT main, STG and PROD deploys.
I have also removed some debugging code from `deploy.sh`
> Improve deploy Github action

- routes/index.js
[[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-XXXX)](https://dsdmoj.atlassian.net/browse/EL-2241)
As part of EL-2241 we need to test that the alerting system is working. So therefore we need to add a quick test route to ensure that is capturing 5XX errors.
> Adds test route for 500 error

- .github/workflows/deploy.yml
- infrastructure/laa-manage-your-civil-cases-uat/ingress-dashboard.yaml
- infrastructure/laa-manage-your-civil-cases-uat/pods-dashboard.yaml
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-2242)
> Grafana infastructure scripts 

- README.md
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2246)
The changes include the addition of TypeScript-specific instructions, updates to reflect TypeScript usage in the project setup, and improvements to the structure and content of the documentation.
> EL-2246 -TypeScript - Final Cleanup

- .github/workflows/gajira.yml
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-2287)
- If applied, this adds Jira integration for MCC
- The repository env/secrets has aslo been added.  
> EL-2287: Jira integration for MCC

- .github/workflows/dependency-review.yml
- .github/workflows/deploy.yml
- .github/workflows/mocha.yml
- .github/workflows/playwright.yml
- package-lock.json
- package.json
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2361)
This pull request updates various dependencies across workflows and the `package.json` file to use newer versions. These changes aim to improve security, compatibility, and performance. The updates include GitHub Actions versions, AWS credentials configuration, caching actions, and several npm packages.
* [`.github/workflows/dependency-review.yml`](diffhunk://#diff-7cdd3ccec44c8ba176bdc3b9ef54c3f56aa210a1a4e2bb5f79d87b1e50314a18L21-R26): Updated the `dependency-review-action` to version `v4.7.1` for improved dependency scanning. Also renamed the "Checkout" step to "Checkout code" for clarity.
* `.github/workflows/deploy.yml`: 
- Updated `setup-node` to version `v4` to support the latest Node.js features. …
> EL-2361  Dependabot PR updates

- deploy/laa-manage-your-civil-cases/values/production.yaml
- deploy/laa-manage-your-civil-cases/values/staging.yaml
- deploy/laa-manage-your-civil-cases/values/uat.yaml
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2393)
This pull request updates Kubernetes configuration files for the `laa-manage-your-civil-cases` application across multiple environments (`production`, `staging`, and `uat`). The changes focus on improving security settings and defining resource limits and requests for better performance and stability.
* Updated `podSecurityContext` and `securityContext` in `production.yaml`, `staging.yaml`, and `uat.yaml` to enforce stricter security policies, including running pods as non-root users, dropping all capabilities, and using the `RuntimeDefault` seccomp profile. [[1]](diffhunk://#diff-5e0832c5f0dc00c85d6d9a5dc33588f838b6e682f0d63055163db788cc624675L28-R44) [[2]](diffhunk://#diff-07fdc20872c6867fa73b9508f0e7cc8946e4b8e78956298df6b73ffb4 …
> EL-2393 -  Update Kubernetes Deployment to Comply with PodSecurity policy

- README.md
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-2250)
Since we have updated the dockerfile to run node public/app.js instead of npm start, no code changes were required in order for a developer to be able to run the application as a docker image in a container locally. I have therefore just updated the readme with some basic instructions.
next steps:
docker compose?
> EL-2250: running locally with docker

- tests/fixtures/cases/accepted/data-asc.json
- tests/fixtures/cases/accepted/data-desc.json
- tests/fixtures/cases/closed/data-asc.json
- tests/fixtures/cases/closed/data-desc.json
- tests/fixtures/cases/new/data-asc.json
- tests/fixtures/cases/new/data-desc.json
- tests/fixtures/cases/opened/data-asc.json
- tests/fixtures/cases/opened/data-desc.json
[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-2336)
This pull request adds fixture data to support UI implementation. Since each UI action (e.g. sorting table columns in ascending or descending order, pagination, tabs ) triggers an API call, the fixture data is structured to closely simulate real API responses. 
The data is placed in the tests directory so it can be reused for unit tests once the real API implementation is in place.
> EL-2336 Adds dummy data for UI implementation

- routes/yourCases.ts
- src/scss/components/_pagination.scss
- src/scss/main.scss
- views/cases/_accepted-partial.njk
- views/cases/_closed-partial.njk
- views/cases/_new-partial.njk
- views/cases/_opened-partial.njk
- views/cases/index.njk
- views/components/paginationComponent.njk
- views/components/sortableTableComponent.njk
- views/components/tabComponent.njk
[Jira ticket ](https://dsdmoj.atlassian.net/browse/EL-2322)
> EL-2322 Adds pagination component

- views/base.njk
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-2481)
- If applied, this removes the pointer events for the e-mail of user - giving the impression it is plain text and not a link.
- n/a
> EL-2481: Change username to plain text

- playwright.config.ts
- routes/yourCases.ts
- tests/e2e/shared/table-sorting-shared-test.ts
- tests/e2e/your-cases-page.spec.ts
- tests/fixtures/cases/accepted/data-asc.json
- tests/fixtures/cases/accepted/data-desc.json
- tests/fixtures/cases/all-client-details.json
- tests/fixtures/cases/new/data-asc.json
- tests/fixtures/cases/new/data-desc.json
- views/cases/_accepted-partial.njk
- views/cases/_closed-partial.njk
- views/cases/_new-partial.njk
- views/cases/_opened-partial.njk
[Jira ticket ](https://dsdmoj.atlassian.net/browse/EL-2497)
> EL-2497 Further fixes to sortOrder and Dummy Data

- package.json
- yarn.lock
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-2492)
- If applied, this updates "@types/node" to 24.0.12
- resolves this PR -> https://github.com/ministryofjustice/laa-manage-your-civil-cases/pull/139
> EL-2492: Updates "@types/node" to 24.0.12

- .github/dependabot.yml
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-2438)
- If applied, this creates a `combined-dependencies` group for each of the package ecosystems we have in this repo.
- Have removed `bundler`, `pip` and `gomod` as they are not relevant for this repo.
> EL-2438: Group MCC Dependabot updates

- routes/editClientDetails.ts
- src/scripts/controllers/editClientDetailsController.ts
- src/scripts/helpers/formValidationRules.ts
- tests/e2e/client_detials_edit_email_address.spec.ts
- types/form-validation.ts
- views/case_details/_client-details-partial.njk
- views/case_details/edit-client-email-address.njk
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-2454)
- If applied, this adds a way for the user change user email address
- Have had to adjust the `src/scripts/helpers/formValidationRules.ts` file, as when calling the `getValidatedFormResult` function using `types/form-validation.ts`, it was expecting all the fields to be part of the arguments. 
> EL-2454: Change client email address

- .github/workflows/mocha.yml
- eslint.config.js
- playwright.config.ts
- src/scripts/controllers/editClientDetailsController.ts
- tests/unit/controllers/caseDetailsController.spec.ts
- tests/unit/controllers/editClientDetailsController.spec.ts
- tests/unit/controllers/yourCasesController.spec.ts
- tests/unit/helpers/formValidationRules.spec.ts
- tests/unit/helpers/validateForm.spec.ts
- tsconfig.json
- types/csrf-types.ts
[EL-2562](https://dsdmoj.atlassian.net/browse/EL-2562)
This commit introduces general test infrastructure improvements as a pre-requisite to enable EL-2457-client-date-of-birth-editing branch to pass the 67% code coverage gate.
The DOB editing branch (EL-2457-client-date-of-birth-editing) requires 67% function coverage to pass CI. Rather than mixing general infrastructure improvements with feature-specific code, this separate branch provides more general test improvements.
- Form validation tests (formValidationRules.spec.ts, validateForm.spec.ts)
- Controller test coverage for caseDetailsController, editClientDetailsController, yourCasesController
- TypeScript CSRF type definitions to resolve import compilation errors
- Tests cover edge cases, error scenarios, and return structure …
> EL-2562: Chore: add tests to improve code coverage

- src/middlewares/searchInputSchema.ts
- tests/e2e/search.spec.ts
- views/components/sortableTableComponent.njk
- views/search/index.njk
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-2589)
This pull request updates user-facing messages and table cell rendering to improve clarity and usability in the case search workflow. The main changes focus on clearer instructions for users and better handling of sensitive information in table displays.
**User-facing message updates:**
* Changed validation error messages in `validateSearchInput` to instruct users to "Enter some case details" instead of "Enter at least one search criteria", making the prompt more specific and user-friendly.
* Updated the search page instruction in `views/search/index.njk` to "Enter case details to search for a case" for consistency and clarity.
**Table rendering improvements:**
* Updated `sortableTableComponent.njk` so that when …
> EL-2589 Amends search page content

- README.md
- src/middlewares/clientEmailAddressSchema.ts
- src/middlewares/clientNameSchema.ts
- views/case_details/edit-client-email-address.njk
- views/case_details/edit-client-name.njk
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-2625)
- This removes highlighted field when no inline error displayed
- This also adds in the content page links for coverage and accessibility testing
> EL-2625: Remove highlighted field when no inline error displayed

- .github/workflows/publish-documentation.yml
- docs/makefile
Reverts ministryofjustice/laa-manage-your-civil-cases#244
The container couldn't be pulled from the repo. reverting to debug.
> Revert "Chore/el 2592 actions checkout upgrade"

- .github/workflows/publish-documentation.yml
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-XXX)
> fixing to use correct deploy method

- locales/en.json
- src/services/apiService.ts
- types/case-types.ts
- views/case_details/_client-details-partial.njk
- views/components/summaryCardComponent.njk
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-2560)
If applied:
- this adds the 'Client support needs' summary card and CTA button
- skips building the row in `Client support needs` summary card when the value is empty or "no"
- n/a
> EL-2560: 'Client support needs' summary card & CTA button

- locales/en.json
- routes/caseDetails.ts
- src/scripts/controllers/index.ts
- src/scripts/controllers/removeClientSupportNeeds.ts
- src/services/apiService.ts
- tests/unit/controllers/removeClientSupportNeeds.spec.ts
- views/case_details/confirm-remove-client-support-needs.njk
- views/components/confirmationComponent.njk
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-2565)
- If applied, this adds an interstitial page to remove client support needs
- n/a
> EL-2565: Remove client support needs interstitial page & functionality

- views/base.njk
- views/case_details/client_support_needs/_base-client-support-needs.njk
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-2670)
- If applied, this adds a fix to clear accessible autocomplete selection when input is empty
- n/a
> EL-2670: Accessible autocomplete clears selection, when input is empty

- .github/workflows/dependency-review.yml
[Jira ticket (if applicable)](https://dsdmoj.atlassian.net/browse/EL-2677)
- If applied this updates the dependency-review-action to 4.8.0
- this will update this pr -> https://github.com/ministryofjustice/laa-manage-your-civil-cases/pull/292
> EL-2677: Update dependency-review-action to 4.8.0
